version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: rustdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5444:5432
    restart: unless-stopped